# Generated by Django 6.0.3 on 2026-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('process_time', models.FloatField(blank=True, null=True)),
                ('topics_count', models.IntegerField(default=0)),
                ('keywords_count', models.IntegerField(default=0)),
            ],
        ),
    ]
