# Generated by Django 6.0.3 on 2026-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='keywords_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='topics_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
