# Generated by Django 6.0.3 on 2026-03-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_legaldocument_keywords_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='mindmap_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
