# Generated by Django 5.2.12 on 2026-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_legaldocument_mindmap_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('publish_date', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('raw_html_path', models.CharField(blank=True, default='', max_length=500)),
                ('ocr_html_path', models.CharField(blank=True, default='', max_length=500)),
                ('topics_count', models.IntegerField(default=0)),
                ('keywords_count', models.IntegerField(default=0)),
                ('topics_list', models.JSONField(blank=True, default=list)),
                ('keywords_list', models.JSONField(blank=True, default=list)),
                ('mindmap_data', models.JSONField(blank=True, default=list)),
                ('ai_topics', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('process_time', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Article',
                'verbose_name_plural': 'Blog Articles',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='ai_topics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='html_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
