# Generated by Django 5.2.12 on 2026-04-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogarticle_legaldocument_ai_topics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='master_topics',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='core.mastertopic'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='master_topics',
            field=models.ManyToManyField(blank=True, related_name='documents', to='core.mastertopic'),
        ),
    ]
