# Generated by Django 5.2.12 on 2026-04-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mastertopic_blogarticle_master_topics_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterTopic',
            new_name='TopicMaster',
        ),
        migrations.AlterModelOptions(
            name='topicmaster',
            options={'verbose_name': 'Topic Master'},
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='master_topics',
        ),
        migrations.RemoveField(
            model_name='legaldocument',
            name='master_topics',
        ),

        migrations.AlterModelTable(
            name='topicmaster',
            table='topic_master',
        ),
    ]
