# Generated by Django 5.2.12 on 2026-04-06 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_mastertopic_topicmaster_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Blog Article', 'verbose_name_plural': 'Blog Articles'},
        ),
        migrations.AlterModelOptions(
            name='topicmaster',
            options={},
        ),
        migrations.CreateModel(
            name='BlogTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_ID', models.ForeignKey(db_column='Blog_ID', on_delete=django.db.models.deletion.CASCADE, to='core.blogarticle')),
                ('Topic_Id', models.ForeignKey(db_column='Topic_Id', on_delete=django.db.models.deletion.CASCADE, to='core.topicmaster')),
            ],
            options={
                'db_table': 'blog_topics',
            },
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='blogs', through='core.BlogTopic', to='core.topicmaster'),
        ),
        migrations.CreateModel(
            name='DocumentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_ID', models.ForeignKey(db_column='Document_ID', on_delete=django.db.models.deletion.CASCADE, to='core.legaldocument')),
                ('Topic_Id', models.ForeignKey(db_column='Topic_Id', on_delete=django.db.models.deletion.CASCADE, to='core.topicmaster')),
            ],
            options={
                'db_table': 'document_topics',
            },
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='documents', through='core.DocumentTopic', to='core.topicmaster'),
        ),
    ]
