# Generated by Django 5.2.12 on 2026-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_blogarticle_options_alter_topicmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_exports/'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='source_xmls/'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_exports/'),
        ),
    ]
