# Generated by Django 5.2.12 on 2026-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogarticle_text_file_legaldocument_source_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='text_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='text_exports/'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='source_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='source_xmls/'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='text_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='text_exports/'),
        ),
    ]
