# Generated by Django 5.2.12 on 2026-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_blogarticle_text_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='source_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='source_xmls/'),
        ),
    ]
